/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.wonderskool.bo.utility.upload;

import java.awt.Color;
import java.awt.EventQueue;
import java.io.File;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.JFileChooser;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.filechooser.FileNameExtensionFilter;

import com.wonderskool.bo.excel.ExcelWriterTest;
import com.wonderskool.bo.excel.StudentMarksExcelReader;
import com.wonderskool.bo.utility.QueryCollection;
import com.wonderskool.bo.utility.TableModels;
import com.wonderskool.bo.utility.TraitVariablesLst;
import com.wonderskool.bo.utility.Utility;
import com.wonderskool.inlead.bo.validate.DBValidateUtility;

/**
 * 
 * @author abhishekmitt
 */
public class StudentMarksUpload extends javax.swing.JFrame {

	private File selectedFile = null;

	/**
	 * Creates new form StudentMarksUploadNew
	 */
	public StudentMarksUpload() {
		com.wonderskool.bo.utility.TableModels.secondColName = "Column No.";
		TraitVariablesLst.initModel();
		initComponents();
		this.jTextArea1.setVisible(false);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jLabel1 = new javax.swing.JLabel();
		jTextField1 = new javax.swing.JTextField();
		jScrollPane2 = new javax.swing.JScrollPane();
		miTbl = new javax.swing.JTable();
		jScrollPane3 = new javax.swing.JScrollPane();
		cmplxPrsTbl = new javax.swing.JTable();
		jScrollPane5 = new javax.swing.JScrollPane();
		qualityTbl = new javax.swing.JTable();
		jScrollPane4 = new javax.swing.JScrollPane();
		abilityTbl = new javax.swing.JTable();
		appendCb = new javax.swing.JCheckBox();
		jButton2 = new javax.swing.JButton();
		jButton3 = new javax.swing.JButton();
		jButton1 = new javax.swing.JButton();
		jScrollPane1 = new javax.swing.JScrollPane();
		jTextArea1 = new javax.swing.JTextArea();
		errMsgLbl = new javax.swing.JLabel();
		jScrollPane6 = new javax.swing.JScrollPane();
		motivatorTable = new javax.swing.JTable();
		jScrollPane7 = new javax.swing.JScrollPane();
		workingStyleTbl = new javax.swing.JTable();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
		jLabel1.setText("Uplaod File:");

		jTextField1.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				jTextField1uplaodTxtClicked(evt);
			}
		});

		miTbl.setModel(new TableModels.MITableModel());
		miTbl.setRowHeight(20);
		jScrollPane2.setViewportView(miTbl);

		cmplxPrsTbl.setModel(new TableModels.CmplxPersTableModel());
		cmplxPrsTbl.setRowHeight(20);
		jScrollPane3.setViewportView(cmplxPrsTbl);

		qualityTbl.setModel(new TableModels.QualityTableModel());
		qualityTbl.setRowHeight(20);
		jScrollPane5.setViewportView(qualityTbl);

		abilityTbl.setModel(new TableModels.AbilityTableModel());
		abilityTbl.setRowHeight(20);
		jScrollPane4.setViewportView(abilityTbl);

		appendCb.setText("Overwrite previous data?");

		jButton2.setMnemonic('C');
		jButton2.setText("Cancel");
		jButton2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton2ActionPerformed(evt);
			}
		});

		jButton3.setText("Download Template");
		jButton3.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton3ActionPerformed(evt);
			}
		});

		jButton1.setMnemonic('P');
		jButton1.setText("Process");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});

		jTextArea1.setEditable(false);
		jTextArea1.setColumns(20);
		jTextArea1.setRows(5);
		jTextArea1.setEnabled(false);
		jScrollPane1.setViewportView(jTextArea1);

		motivatorTable.setModel(new TableModels.MotivatorTableModel());
		motivatorTable.setRowHeight(20);
		jScrollPane6.setViewportView(motivatorTable);

		workingStyleTbl.setModel(new TableModels.WorkingStyleTableModel());
		workingStyleTbl.setRowHeight(20);
		jScrollPane7.setViewportView(workingStyleTbl);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addContainerGap()
								.addGroup(
										layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(
														layout.createSequentialGroup()
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING,
																				false)
																				.addComponent(
																						jScrollPane2,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						229, Short.MAX_VALUE)
																				.addComponent(
																						jScrollPane4,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						0, Short.MAX_VALUE))
																.addGap(9, 9, 9)
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING,
																				false)
																				.addComponent(
																						jScrollPane5,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						239, Short.MAX_VALUE)
																				.addComponent(
																						jScrollPane3,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						0, Short.MAX_VALUE))
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																		10, Short.MAX_VALUE)
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING,
																				false)
																				.addComponent(
																						jScrollPane7,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						258, Short.MAX_VALUE)
																				.addComponent(
																						jScrollPane6,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						0, Short.MAX_VALUE))
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING)
																				.addComponent(
																						jScrollPane1,
																						javax.swing.GroupLayout.Alignment.TRAILING,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						javax.swing.GroupLayout.PREFERRED_SIZE)
																				.addGroup(
																						layout.createSequentialGroup()
																								.addComponent(
																										appendCb,
																										javax.swing.GroupLayout.PREFERRED_SIZE,
																										223,
																										javax.swing.GroupLayout.PREFERRED_SIZE)
																								.addGap(0, 0,
																										Short.MAX_VALUE))))
												.addGroup(
														layout.createSequentialGroup()
																.addComponent(jButton1,
																		javax.swing.GroupLayout.PREFERRED_SIZE, 82,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addComponent(jButton3)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addComponent(jButton2,
																		javax.swing.GroupLayout.PREFERRED_SIZE, 82,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addGap(0, 0, Short.MAX_VALUE))
												.addGroup(
														layout.createSequentialGroup()
																.addComponent(jLabel1,
																		javax.swing.GroupLayout.PREFERRED_SIZE, 68,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addComponent(jTextField1,
																		javax.swing.GroupLayout.PREFERRED_SIZE, 157,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addGap(224, 224, 224)
																.addComponent(errMsgLbl,
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		Short.MAX_VALUE))).addContainerGap()));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				layout.createSequentialGroup()
						.addContainerGap()
						.addGroup(
								layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(jLabel1)
										.addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE).addComponent(errMsgLbl))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(
								layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addGroup(
												layout.createSequentialGroup()
														.addGap(105, 105, 105)
														.addComponent(jScrollPane1,
																javax.swing.GroupLayout.PREFERRED_SIZE, 320,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addPreferredGap(
																javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59,
																Short.MAX_VALUE).addComponent(appendCb))
										.addGroup(
												layout.createSequentialGroup()
														.addGroup(
																layout.createParallelGroup(
																		javax.swing.GroupLayout.Alignment.LEADING)
																		.addComponent(jScrollPane6,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				0, Short.MAX_VALUE)
																		.addComponent(jScrollPane2,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				0, Short.MAX_VALUE)
																		.addComponent(jScrollPane3,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				0, Short.MAX_VALUE))
														.addPreferredGap(
																javax.swing.LayoutStyle.ComponentPlacement.RELATED)
														.addGroup(
																layout.createParallelGroup(
																		javax.swing.GroupLayout.Alignment.LEADING,
																		false)
																		.addComponent(jScrollPane4,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				264, Short.MAX_VALUE)
																		.addComponent(jScrollPane5,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				0, Short.MAX_VALUE)
																		.addComponent(jScrollPane7,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				0, Short.MAX_VALUE))))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(
								layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(jButton1).addComponent(jButton2).addComponent(jButton3))
						.addContainerGap()));

		errMsgLbl.getAccessibleContext().setAccessibleName("errMsgLbl");

		pack();
	}// </editor-fold>

	private void jTextField1uplaodTxtClicked(java.awt.event.MouseEvent evt) {
		JFileChooser chooser = new JFileChooser();
		chooser.setFileFilter(new FileNameExtensionFilter("Excel", new String[] { "xls" }));
		int returnVal = chooser.showOpenDialog(this);
		if (returnVal != 0) {
			return;
		}
		this.selectedFile = chooser.getSelectedFile();
		if ((this.selectedFile == null) || (!this.selectedFile.exists())) {
			this.errMsgLbl.setText("Error:Invalid/No file selected!!!");
			return;
		}
		this.jTextField1.setText(this.selectedFile.getAbsolutePath());
	}

	private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
		Utility.callCancel(this);
	}

	private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {
		if (this.selectedFile == null) {
			this.errMsgLbl.setText("Error:No file selected!!!");
			return;
		}
		File actualFile = new File(this.selectedFile.getParent(), "stuResultTemplate.xls");
		try {
			ExcelWriterTest.write(actualFile, "Enroll No");
			this.errMsgLbl.setText("Info:Generated File-" + actualFile.getAbsolutePath());
		} catch (Exception e) {
			this.errMsgLbl.setText("Error:" + e.getMessage());
		}
	}

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
		if (this.selectedFile == null) {
			this.errMsgLbl.setText("Error:No file selected!!!");
			return;
		}

		if (!DBValidateUtility.validUserAccess("upload_marks_write", this.errMsgLbl))
			return;
		HashMap miMap = new HashMap();
		HashMap cmplxPersMap = new HashMap();
		HashMap abilityMap = new HashMap();
		HashMap qualityMap = new HashMap();

		for (int i = 0; i < this.miTbl.getRowCount(); i++) {
			miMap.put(this.miTbl.getValueAt(i, 0).toString(),
					Integer.valueOf(Utility.parseInteger(this.miTbl.getValueAt(i, 1).toString())));
		}

		for (int i = 0; i < this.cmplxPrsTbl.getRowCount(); i++) {
			cmplxPersMap.put(this.cmplxPrsTbl.getValueAt(i, 0).toString(),
					Integer.valueOf(Utility.parseInteger(this.cmplxPrsTbl.getValueAt(i, 1).toString())));
		}

		for (int i = 0; i < this.abilityTbl.getRowCount(); i++) {
			abilityMap.put(this.abilityTbl.getValueAt(i, 0).toString(),
					Integer.valueOf(Utility.parseInteger(this.abilityTbl.getValueAt(i, 1).toString())));
		}

		for (int i = 0; i < this.qualityTbl.getRowCount(); i++)
			qualityMap.put(this.qualityTbl.getValueAt(i, 0).toString(),
					Integer.valueOf(Utility.parseInteger(this.qualityTbl.getValueAt(i, 1).toString())));
		try {
			if (!Utility.getjdbcconnection(this.errMsgLbl))
				return;
			if (!this.appendCb.isSelected()) {
				Utility.conn.createStatement().executeUpdate(QueryCollection.STUDENT_RESULT.DELETE_EXISTING_DATA);
			}
			String result = new StudentMarksExcelReader().read(this.selectedFile.getAbsolutePath(), miMap,
					cmplxPersMap, abilityMap, qualityMap, this.errMsgLbl);
			if (!Utility.isNullEmpty(result)) {
				this.jTextArea1.setVisible(true);
				this.jTextArea1.setText(result);
				this.jTextArea1.setEditable(false);
				this.errMsgLbl.setText("Info:Some data cannot be saved due to errors!!!");
			} else {
				this.jTextArea1.setVisible(false);
				this.errMsgLbl.setText("Info:Data saved successfully!!!");
			}
			Utility.finishjdbcconnection();
		} catch (Exception ex) {
			ex.printStackTrace();
			this.errMsgLbl.setText(ex.getMessage());
			return;
		}
	}

	public static void main(String[] args) {
		try {
			for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels())
				if ("Nimbus".equals(info.getName())) {
					UIManager.setLookAndFeel(info.getClassName());
					break;
				}
		} catch (ClassNotFoundException ex) {
			Logger.getLogger(StudentMarksUpload.class.getName()).log(Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			Logger.getLogger(StudentMarksUpload.class.getName()).log(Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			Logger.getLogger(StudentMarksUpload.class.getName()).log(Level.SEVERE, null, ex);
		} catch (UnsupportedLookAndFeelException ex) {
			Logger.getLogger(StudentMarksUpload.class.getName()).log(Level.SEVERE, null, ex);
		}

		EventQueue.invokeLater(new Runnable() {
			public void run() {
				new StudentMarksUpload().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify
	private javax.swing.JTable abilityTbl;
	private javax.swing.JCheckBox appendCb;
	private javax.swing.JTable cmplxPrsTbl;
	private javax.swing.JLabel errMsgLbl;
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton2;
	private javax.swing.JButton jButton3;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JScrollPane jScrollPane2;
	private javax.swing.JScrollPane jScrollPane3;
	private javax.swing.JScrollPane jScrollPane4;
	private javax.swing.JScrollPane jScrollPane5;
	private javax.swing.JScrollPane jScrollPane6;
	private javax.swing.JScrollPane jScrollPane7;
	private javax.swing.JTextArea jTextArea1;
	private javax.swing.JTextField jTextField1;
	private javax.swing.JTable miTbl;
	private javax.swing.JTable motivatorTable;
	private javax.swing.JTable qualityTbl;
	private javax.swing.JTable workingStyleTbl;
	// End of variables declaration
}
