/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.wonderskool.bo.utility.upload;

import com.wonderskool.bo.excel.CriteriaDataExcelReader;
import com.wonderskool.bo.excel.ExcelWriterTest;
import com.wonderskool.bo.utility.TableModels;
import com.wonderskool.bo.utility.Utility;
import com.wonderskool.inlead.bo.validate.DBValidateUtility;
import java.awt.Color;
import java.io.File;
import java.util.HashMap;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author abhishekmitt
 */
public class UploadProfessionCriteria extends javax.swing.JFrame {

  private File selectedFile = null;
    /**
     * Creates new form UploadProfessionCriteriaNew
     */
    public UploadProfessionCriteria() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
 // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        miTbl = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        cmplxPrsTbl = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        qualityTbl = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        abilityTbl = new javax.swing.JTable();
        appendCb = new javax.swing.JCheckBox();
        strmTxt = new javax.swing.JTextField();
        strmLbl = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        motivatorTable = new javax.swing.JTable();
        jScrollPane7 = new javax.swing.JScrollPane();
        workingStyleTbl = new javax.swing.JTable();
        errMsgLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Uplaod File:");

        jTextField1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField1uplaodTxtClicked(evt);
            }
        });

        miTbl.setModel(new TableModels.MITableModel());
        miTbl.setRowHeight(20);
        jScrollPane2.setViewportView(miTbl);

        cmplxPrsTbl.setModel(new TableModels.CmplxPersTableModel());
        cmplxPrsTbl.setRowHeight(20);
        jScrollPane3.setViewportView(cmplxPrsTbl);

        qualityTbl.setModel(new TableModels.QualityTableModel());
        qualityTbl.setRowHeight(20);
        jScrollPane5.setViewportView(qualityTbl);

        abilityTbl.setModel(new TableModels.AbilityTableModel());
        abilityTbl.setRowHeight(20);
        jScrollPane4.setViewportView(abilityTbl);

        appendCb.setText("Overwrite previous data?");

        strmLbl.setText("Stream:");

        jButton1.setText("Process");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setText("Download Template");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        motivatorTable.setModel(new TableModels.MotivatorTableModel());
        motivatorTable.setRowHeight(20);
        jScrollPane6.setViewportView(motivatorTable);

        workingStyleTbl.setModel(new TableModels.WorkingStyleTableModel());
        workingStyleTbl.setRowHeight(20);
        jScrollPane7.setViewportView(workingStyleTbl);

        errMsgLbl.setForeground(Color.RED);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(errMsgLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE)
                                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 241, Short.MAX_VALUE)
                                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(strmLbl)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(strmTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(appendCb, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addGap(72, 72, 72)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel1))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(errMsgLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(appendCb)
                                .addGap(3, 3, 3)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(strmLbl)
                                    .addComponent(strmTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton3)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>                          

    private void jTextField1uplaodTxtClicked(java.awt.event.MouseEvent evt) {                                             
        JFileChooser chooser = new JFileChooser();
    chooser.setFileFilter(new FileNameExtensionFilter("Excel", new String[] { "xls", "xlsx" }));
    int returnVal = chooser.showOpenDialog(this);
    if (returnVal != 0) {
      return;
    }
    this.selectedFile = chooser.getSelectedFile();
    if ((this.selectedFile == null) || (!this.selectedFile.exists())) {
      this.errMsgLbl.setText("Error:Invalid/No file selected!!!");
      return;
    }
    this.jTextField1.setText(this.selectedFile.getAbsolutePath());
    }                                            

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        if (this.selectedFile == null) {
      this.errMsgLbl.setText("Error:No file selected!!!");
      return;
    }
    if ((Utility.isNullEmpty(this.strmTxt.getText())) || (!Utility.isNumeric(this.strmTxt.getText()))) {
      this.errMsgLbl.setText("Error:Invalid Stream col specified!!!");
      return;
    }
    if (!DBValidateUtility.validUserAccess("upload_profession_write", this.errMsgLbl))
      return;
    HashMap miMap = new HashMap();
    HashMap cmplxPersMap = new HashMap();
    HashMap abilityMap = new HashMap();
    HashMap qualityMap = new HashMap();

    for (int i = 0; i < this.miTbl.getRowCount(); i++) {
      miMap.put(this.miTbl.getValueAt(i, 0).toString(), Integer.valueOf(Utility.parseInteger(this.miTbl.getValueAt(i, 1).toString())));
    }

    for (int i = 0; i < this.cmplxPrsTbl.getRowCount(); i++) {
      cmplxPersMap.put(this.cmplxPrsTbl.getValueAt(i, 0).toString(), Integer.valueOf(Utility.parseInteger(this.cmplxPrsTbl.getValueAt(i, 1).toString())));
    }

    for (int i = 0; i < this.abilityTbl.getRowCount(); i++) {
      abilityMap.put(this.abilityTbl.getValueAt(i, 0).toString(), Integer.valueOf(Utility.parseInteger(this.abilityTbl.getValueAt(i, 1).toString())));
    }

    for (int i = 0; i < this.qualityTbl.getRowCount(); i++) {
      qualityMap.put(this.qualityTbl.getValueAt(i, 0).toString(), Integer.valueOf(Utility.parseInteger(this.qualityTbl.getValueAt(i, 1).toString())));
    }
    try
    {
      if (!Utility.getjdbcconnection(this.errMsgLbl))
        return;
      if (!this.appendCb.isSelected()) {
        Utility.conn.createStatement().executeUpdate("DELETE FROM profession_criteria");
        Utility.conn.createStatement().executeUpdate("DELETE FROM profession_stream_tbl");
      }
      new CriteriaDataExcelReader().read(this.selectedFile.getAbsolutePath(), miMap, cmplxPersMap, abilityMap, qualityMap, Integer.parseInt(this.strmTxt.getText()));
      Utility.finishjdbcconnection();
      this.errMsgLbl.setText("Info:Data ported successfully!!!");
    } catch (Exception ex) {
      ex.printStackTrace();
      this.errMsgLbl.setText(ex.getMessage());
      return;
    }
    }                                        

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        if (this.selectedFile == null) {
      this.errMsgLbl.setText("Error:No file selected!!!");
      return;
    }
    File actualFile = new File(this.selectedFile.getParent(), "professionTemplate.xls");
    try {
      ExcelWriterTest.write(actualFile, "Profession");
      this.errMsgLbl.setText("Info:Generated File-" + actualFile.getAbsolutePath());
    }
    catch (Exception e) {
      this.errMsgLbl.setText("Error:" + e.getMessage());
    }
    }                                        

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        Utility.callCancel(this);
    }                                        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UploadProfessionCriteria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UploadProfessionCriteria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UploadProfessionCriteria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UploadProfessionCriteria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display tjLabel2he form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UploadProfessionCriteria().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify                     
    private javax.swing.JTable abilityTbl;
    private javax.swing.JCheckBox appendCb;
    private javax.swing.JTable cmplxPrsTbl;
    private javax.swing.JLabel errMsgLbl;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTable miTbl;
    private javax.swing.JTable motivatorTable;
    private javax.swing.JTable qualityTbl;
    private javax.swing.JLabel strmLbl;
    private javax.swing.JTextField strmTxt;
    private javax.swing.JTable workingStyleTbl;
    // End of variables declaration                   
}
